---
- hosts: "{{ hosts }}"
  become: true
  tasks:
  - name: Instalamos apache
    package:
      name: httpd
      state: latest
  - name: iniciamos servicio y configuramos en arranque
    service:
      name: httpd
      state: started
      enabled: yes
  - name: creamos la pagina de inicio 
    file:
      path: /var/www/html/index.html
      state: touch
  - name: añadimos contenido al fichero
    copy:
      content: "HOla!!!!"
      dest: /var/www/html/index.html

