---
- hosts: web
  become: true
  tasks:
  - name: lanzo un mensaje
    debug:
      msg: "servidores web"
- hosts: bd
  become: true
  tasks:
  - name: lanzo un mensaje
    debug:
      msg: "servidores bd"
