---
- hosts: "{{ hosts }}"
  tasks:
  # - name: contenido variable
  #   debug:
  #      msg: "valor variable rol: {{ rol }} y su password es: {{ password }}"
  - name: contenido variable var
    debug:
      msg: "var: {{ var_formacion  }}"