--- 
- hosts: all
  become: true
  vars:
    pepe: 2
    var: 1
  serial:
  - 1
  - 2
  - 50%
  max_fail_percentage: 20
  tasks:
  - name: curl 
    uri:
      url: "http://{{ inventory_hostname }}"
    